os: linux
dist: focal
language: python
python:
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - node_modules
before_install:
- set -e
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install
- python3 --version
- pip3 --version
script:
  - npm run lint
  - npm run lint-test
  - npm test
#  - tox -e qa
after_success: npm run coverage
